sudo: required
dist: trusty
language: java
jdk:
- oraclejdk8
cache:
  directories:
  - '$HOME/.m2/repository'

install:
  # install aws cli
  - sudo apt-get -y install python-pip
  - sudo pip install awscli
  - aws --version

script: mvn clean test -Dspring.profiles.active=test

after_success:
  # Parse branch name and determine an environment to deploy
  - export ENV=$(echo "${TRAVIS_BRANCH}" | perl -ne "print $& if /(?<=deploy\/).*/")
  # Switch AWS Role when ENV is prod
  - test "${ENV}" = "prod" && source scripts/switch-production-role.sh

deploy:
  - provider: script
    script: scripts/deploy.sh
    skip_cleanup: true
    on:
      branch: deploy/*
